# -*- coding: utf-8 -*-
"""translation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OIqDwHQZGeAICUqC8EspQ38gXnnld1H4
"""

!pip install googletrans==3.1.0a0

dataset_bg = pd.read_csv('/content/CT22_bulgarian_1B_harmful_train.tsv', delimiter = '\t')

from googletrans import Translator
translator= Translator()

for index_label, row_series in dataset_bg.iterrows():
  dataset_bg.at[index_label, 'tweet_text']= translator.translate(dataset_bg.at[index_label, 'tweet_text'], src='bg', dest='en').text
  # print(dataset_bg.at[index_label, 'tweet_text'])

dataset_bg.to_csv('xyz.csv')

dataset_en = pd.read_csv('/content/CT22_english_1B_harmful_train.tsv', delimiter = '\t')

dataset_en  = dataset_en.append(dataset_bg, ignore_index=True)

dataset_en.to_csv('xyz.csv')

dataset_nl =  pd.read_csv('/content/CT22_dutch_1B_harmful_train.tsv', delimiter = '\t')

for index_label, row_series in dataset_nl.iterrows():
  dataset_nl.at[index_label, 'tweet_text']= translator.translate(dataset_nl.at[index_label, 'tweet_text'], src='nl', dest='en').text
  # print(dataset_bg.at[index_label, 'tweet_text'])

dataset_en  = dataset_en.append(dataset_nl, ignore_index=True)

import re 
for index_label, row_series in dataset_en.iterrows():
  text = dataset_en.at[index_label, 'tweet_text']
  # HASHTAGS
  text = re.sub(r"#\S+","",text)
  # URLS
  text = re.sub(r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))","",text)
  #MENTIONS
  text = re.sub(r"@\S+","",text)
  # NUMBERS CHANGE eg 30 --> "number"
  text = re.sub('(?:^|\s)(?=.)((?:0|(?:[1-9](?:\d*|\d{0,2}(?:,\d{3})*)))?(?:\.\d*[1-9])?)(?!\S)'," number ",text)
  #FORMATTED NUMBER: with decimals/commas
  #finally putting it back in its place
  dataset_en.at[index_label, 'tweet_text'] = text

dataset_en.to_csv('task1btestraw.csv' , index = False)