# -*- coding: utf-8 -*-
"""twitterapi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SstuUsnhy39b0U1JpqbV_aMEsHIJ16ZX
"""

import tweepy
import pandas as pd
import re
import time

bearer_token = ""
API_KEY = ""
API_SECRET = ""
ACCESS_TOKEN = ""
ACCESS_TOKEN_SECRET = ""

auth = tweepy.OAuth1UserHandler(
   API_KEY, API_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET
)

api = tweepy.API(auth)

dataset = pd.read_csv('/content/task1bvalraw.csv')

regex = r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))"

followers = []
following = []
posts = []
likes = []
rts = []
verified = []
has_url = []
class_label = []

count = 1

for index_label, row_series in dataset.iterrows():
  # tweet_id = dataset.at[index_label,'tweet_id'].va

  count=count+1

  class_label.append(0)

  if count==900:
    time.sleep(1200)
    count=1


  maybe_id = dataset.at[index_label,'tweet_url'].replace("http://twitter.com/user/status/","")
  
  try:
    tweet = api.get_status(id= maybe_id)
    # print(tweet)
    followers.append(tweet.user.followers_count) 
    following.append(tweet.user.friends_count)
    posts.append(tweet.user.statuses_count)
    likes.append(tweet.favorite_count)
    rts.append(tweet.retweet_count)
    verified.append(1 if tweet.user.verified==True  else 0)
    has_url.append(1 if  bool(re.search(regex, tweet.text)) else 0)
    print(index_label)
  except:
    followers.append(0) 
    following.append(0)
    posts.append(0)
    likes.append(0)
    rts.append(0)
    verified.append(00)
    has_url.append(0)
    print("err " + str(index_label))

dataset = dataset.assign(followers = followers,
following = following,
posts = posts,
likes = likes,
rts = rts,
verified = verified,
url = has_url)